### PR TITLE
Remove unnecessary console.log line from PublisherTransport

### PR DESCRIPTION
**Pull request by simonkarman**

### CODE REVIEW

**Comment by simonkarman** [comment]
@jkarneges Do you have time to look at the changes?

**Comment by harmony7** [comment]
This looks good, will publish a new one soon.

**Comment by davidknezic** [comment]
Hey @harmony7, any idea when this can be released and if it's worth forking and publishing a private package with this change in it?

**Review by harmony7 — APPROVED** [review]

**Comment by harmony7** [comment]
Hey, thanks for your patience, I somehow missed this one since I look at it.

I've just released a 3.2.0 that includes this fix, please check it out.

**Comment by davidknezic** [comment]
Wonderful, there's no fetch data leaked to the console anymore. ✨

Thank you so much for your swift response!

**Pull request merged**
